Add Wii port
sharkwouter/oceanpop pull request #73
Opened 2024-03-22 20:25 UTC by mardy

Thanks Wouter for this nice game, it's written very well and it was a pleasure to port it :-)

Please note that in order for the port to be complete, we need a 128x48 icon file (png) and an [XML manifest](https://wiibrew.org/wiki/Homebrew_Channel#Adding_Text). If you can provide them to me (at least the icon and the description text for the manifest), then I can add them to this PR.

We should [submit](https://github.com/OpenShopChannel/Apps/pulls) the game to the Open Shop Channel, then.

2024-03-24 07:12 UTC, mardy commented
Hi Wouter, I went on and created the manifest and icon myself. Please let me know, if they are fine.

I also added a script to make a release. For the time being, I'll put the release on my own fork and submit the app to the Open Shop Channel, but as soon as you decide to support the Wii port in this repository, I'll submit a change so that this will become the reference repo for any future release.

2024-03-24 13:22 UTC, sharkwouter commented
This is so cool, thanks for doing this! I'll take a look at it.

2024-03-24 13:29 UTC, sharkwouter commented on platform/update-platforms.sh
Could you run this script once and add the background to the branch? I know it's not the cleanest solution, but that way the build succeeds without having to do so manually.

2024-03-24 13:37 UTC, sharkwouter requested changes
This is a really good start, I really like the idea of seeing OceanPop on more platforms. I had a couple of comments, which I think would be doable to resolve before merging, but let me know if you have the time to address them. The current work is pretty good and I'm surprised you only needed 1 code change.

One thing I'd like to have added if it is not too much work, would be to add an automated build for the Wii to `.github/workflows/build.yml`. Would that be doable?

2024-03-24 13:37 UTC, sharkwouter commented on platform/wii/icon.png
Could you base this one on `platform/psp/icon0.png`? I think that would look a bit better.

2024-03-24 13:37 UTC, sharkwouter commented on platform/wii/make_release.sh
Would it be possible to build the package using CMake instead?

I would suggest using the `add_custom_command` function in CMake to add post build commands for running the zip command the and the `file` command for copying.

For the config file, I would add `version` as an option (using the `option` function) and use the `configure_file` function to do the substitution.

2024-03-24 20:02 UTC, mardy commented on platform/update-platforms.sh
Done! Though I personally wouldn't do this, since it just makes the git repo bigger for just a small convenience.

2024-03-24 20:03 UTC, mardy commented on platform/wii/icon.png
I added a couple of more items, since otherwise it was looking a bit too lonely. Please let me know if that's OK :-)

2024-03-24 20:07 UTC, mardy commented on platform/wii/make_release.sh
Mmm... While I agree that it would be cleaner, it's also a bit more inconvenient, because you need to set the version number at the time when you run cmake. I can try to do that, but it will take me some more time.

2024-03-24 20:08 UTC, mardy commented
> One thing I'd like to have added if it is not too much work, would be to add an automated build for the Wii to `.github/workflows/build.yml`. Would that be doable?

Done (you can see a run in my fork). I'm not familiar with github actions, though, so let me know if it could be improved. And I have no idea where the artifacts have been uploaded to, so I can't even verify that they are correct :-D

2024-03-24 20:43 UTC, sharkwouter commented on platform/wii/icon.png
Oh cool, looks good!

2024-03-24 20:45 UTC, sharkwouter commented on .github/workflows/build.yml
>      needs: [Linux, Windows, PSP, Vita]
Can you add Wii here? This looks good otherwise. It's working well too.

2024-03-24 20:47 UTC, sharkwouter commented on platform/update-platforms.sh
Yeah, I could've thought of that when I wrote this script initially. I do like that you are not required to have imagemagick to build the application, though. Thanks for making the change!

2024-05-18 20:50 UTC, sharkwouter commented
Sorry for getting back to you so late. I had not seen you made the requested changes. Thanks for that!

2024-05-18 20:50 UTC, merged